apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: observability
  labels:
    app: loki
data:
  rules.yaml: |
    groups:
      - name: logs-alerts
        rules:
          - alert: HighErrorRate
            expr: sum by (app) (rate({app="api"} |= "ERROR" [5m])) > 0
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: Error logs detected for app
              description: More than 0 ERROR lines per 5m for app {{ $labels.app }}
