auth:
  rootUser: minio
  rootPassword: minio123

defaultBuckets: "loki,tempo"

service:
  type: ClusterIP
  ports:
    api: 9000
    console: 9001

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi
